[settings]
trusted_config_paths = ["~/dev", "~/.t3/worktrees"]

[tools]
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
"npm:tree-sitter-cli" = "latest"
pitchfork = "latest"
uv = "latest"
